FILE_DEVICE_VENDOR = 0x8888 # Device Type Limited to: 0x8000 -> 0x7FFFFFFF
FILE_ANY_ACCESS = 0
FILE_SPECIAL_ACCESS = 0
FILE_READ_ACCESS = 1
FILE_WRITE_ACCESS = 2

METHOD_BUFFERED = 0
METHOD_IN_DIRECT = 1
METHOD_OUT_DIRECT = 2
METHOD_NEITHER = 3

IOCTL_COMMON_BIT = 0x80000000
IOCTL_CUSTOM_BIT = 0x00002000
VENDOR_BITMASK = IOCTL_COMMON_BIT | IOCTL_CUSTOM_BIT

def CTL_CODE(DeviceType, Function, Method, Access):
    return ((DeviceType << 16) | (Access << 14) | (Function << 2) | (Method))

def VENDOR_CTL_CODE(CODE, METHOD):
    return CTL_CODE(FILE_DEVICE_VENDOR, CODE, METHOD, FILE_ANY_ACCESS) | VENDOR_BITMASK

# Function Code Limited to: 0x800 -> 0xFFF

IOCTL_SOCKET = VENDOR_CTL_CODE(0x800, METHOD_BUFFERED)
IOCTL_HWTEST = VENDOR_CTL_CODE(0x801, METHOD_BUFFERED)

print("IOCTL_SOCKET:", bin(IOCTL_SOCKET), hex(IOCTL_SOCKET), IOCTL_SOCKET)
print("IOCTL_HWTEST:", bin(IOCTL_HWTEST), hex(IOCTL_HWTEST), IOCTL_HWTEST)
